### PR TITLE
Remove obsolete docs

### PR DESCRIPTION
**Pull request by luator**
## Description

Delete the (outdated) documentation of the following packages:

mpi_cpp_tools: This package is not used anymore.
robot_interfaces: Docs are now hosted at MPI
robot_fingers: Docs are now hosted at MPI
trifinger_simulation: Docs are hosted at readthedocs.io

~Also update links to the new documentations of these packages.~

## How I Tested

Not tested.

### CODE REVIEW

**Comment by luator** [comment]
@MaximilienNaveau I think really relevant for review is only the first commit.  I wasn't able to regenerate the HTML files due to dependency issues.  Do you have a working setup where you could quickly do this?

**Comment by MaximilienNaveau** [comment]
Arf this is not the way to go,
you should modify the python file which generate this index.rst
I am sorry the dirty way will take way too much time, we need to clean toe generation code of this package.

**Comment by luator** [comment]
Oh, I wasn't aware that the index.rst is auto-generated.  I assume, you mean [this Python script](https://github.com/open-dynamic-robot-initiative/open-dynamic-robot-initiative.github.io/blob/master/sphinx_source_files/update_doc_page.py)?
From taking a quick look, this doesn't seem so easy to adjust.  I'll drop the changes on index.rst in this PR, so that we can at least remove the obsolete package documentation for now.

**Comment by MaximilienNaveau** [comment]
:+1: I merge, and I will try to find the time to update the system like I did for the mim doc

**Pull request merged**
